In [ ]:
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np


In [ ]:
mnist = tf.keras.datasets.mnist
(x_train,y_train),(x_test,y_test) = mnist.load_data()

In [ ]:
x_train.shape

(60000, 28, 28)

In [ ]:
y_train.shape

(60000,)

In [ ]:
x_test.shape

(10000, 28, 28)

In [ ]:
y_test.shape

(10000,)

In [ ]:
y_train[89]

4

In [ ]:
import matplotlib.pyplot as plt
plt.imshow(x_train[45])
plt.show

<function matplotlib.pyplot.show>

In [ ]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(512, activation= 'relu'))
model.add(tf.keras.layers.Dense(10, activation= 'softmax'))


In [ ]:
model.compile(optimizer= 'adam', loss = 'sparse_categorical_crossentropy', metrics= 'accuracy')

In [ ]:
history = model.fit(x_train, y_train, epochs= 5)

Epoch 1/5
1875/1875 [==============================] - 7s 4ms/step - loss: 2.7232 - accuracy: 0.9065
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.3490 - accuracy: 0.9381
Epoch 3/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.3088 - accuracy: 0.9414
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2923 - accuracy: 0.9453
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2490 - accuracy: 0.9495


In [ ]:
y_pred = model.predict_classes(x_test)
y_pred

array([7, 2, 1, ..., 4, 5, 6])

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [ ]:
accuracy_score(y_pred,y_test)

0.9475

In [ ]:
confusion_matrix(y_pred, y_test)

array([[ 965,    0,    4,    0,    1,    2,   10,    2,    1,    2],
       [   0, 1104,    1,    0,    1,    0,    4,    4,    0,    3],
       [   0,    6,  968,    4,    5,    0,    2,   16,    5,    0],
       [   0,    2,   16,  974,    0,   28,    1,    9,   32,    8],
       [   1,    2,    5,    0,  906,    1,   11,    1,    1,   16],
       [   3,    1,    1,    4,    0,  823,    6,    2,    2,    1],
       [   4,    1,    4,    0,   12,   17,  917,    0,    7,    0],
       [   1,    2,   12,    6,    6,    1,    0,  973,    2,    5],
       [   5,   17,   20,    7,   10,   13,    7,    7,  879,    8],
       [   1,    0,    1,   15,   41,    7,    0,   14,   45,  966]])

In [ ]:
plt.plot(history.history['accuracy'])

In [ ]:
model.get_weights()

[array([[ 0.05997783,  0.00579887,  0.03254431, ..., -0.06738495,
          0.03370945,  0.00321978],
        [ 0.04731517, -0.04137995,  0.02818035, ...,  0.05560225,
         -0.05654394, -0.01991974],
        [ 0.0519018 ,  0.01370887, -0.01766122, ..., -0.03066178,
          0.06558423,  0.01382761],
        ...,
        [-0.01139948,  0.0030335 , -0.03276825, ..., -0.04576182,
         -0.02816296,  0.0336315 ],
        [-0.04964831, -0.03216216,  0.00708303, ..., -0.05103586,
         -0.03028617,  0.05719958],
        [-0.0671409 ,  0.03589184,  0.04751959, ..., -0.02208893,
         -0.01126   , -0.0551025 ]], dtype=float32),
 array([-0.02046102, -0.05597482, -0.02507842, -0.03696911, -0.0342695 ,
        -0.04164843, -0.05576114, -0.03836847, -0.03897209, -0.02522674,
        -0.0149784 , -0.04322333, -0.03825781, -0.03708939, -0.00416345,
        -0.02129196, -0.04029781, -0.05765985, -0.00932839, -0.04397921,
        -0.03070371, -0.03145958, -0.03140298, -0.03099115, -0.064

In [ ]:
model.save('model_integer.h5')